default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: onehundo_development

test:
  <<: *default
  database: onehundo_test

production:
  <<: *default
  database: onehundo_production
